# Generated by Django 6.0.3 on 2026-04-21 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_wallet_activated_at'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.plan'),
        ),
    ]
